-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."author"
(
    author_id integer NOT NULL,
    full_name character varying NOT NULL,
    PRIMARY KEY (author_id)
);

CREATE TABLE IF NOT EXISTS public."reader"
(
    reader_id integer NOT NULL,
    name character varying NOT NULL,
    email character varying NOT NULL,
    phone character varying NOT NULL,
    PRIMARY KEY (reader_id)
);

CREATE TABLE IF NOT EXISTS public."book"
(
    book_id integer NOT NULL,
    title character varying NOT NULL,
    author_id integer NOT NULL,
    PRIMARY KEY (book_id)
);

CREATE TABLE IF NOT EXISTS public."book_loan"
(
    loan_id integer NOT NULL,
    reader_id integer NOT NULL,
    book_id integer NOT NULL,
    issue_date date NOT NULL,
    due_date date NOT NULL,
    return_date date,
    PRIMARY KEY (loan_id)
);

ALTER TABLE IF EXISTS public."book"
    ADD FOREIGN KEY (author_id)
    REFERENCES public.author (author_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."book_loan"
    ADD FOREIGN KEY (reader_id)
    REFERENCES public.reader (reader_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."book_loan"
    ADD FOREIGN KEY (book_id)
    REFERENCES public.book (book_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;


INSERT INTO author (author_id, full_name) VALUES
(1, 'Тарас Шевченко'),
(2, 'Джордж Орвелл'),
(3, 'Анджей Сапковський');

INSERT INTO reader (reader_id, name, email, phone) VALUES
(1, 'Олександр Коваль', 'o.koval@gmail.com', '+380501112233'),
(2, 'Марія Мельник', 'm.melnyk@gmail.com', '+380672223344'),
(3, 'Іван Бондаренко', 'i.bond@gmail.com', '+380933334455');

INSERT INTO book (book_id, title, author_id) VALUES
(1, 'Кобзар', 1),
(2, '1984', 2),
(3, 'Скотоферма', 2),
(4, 'Відьмак: Останнє бажання', 3);

INSERT INTO book_loan (loan_id, reader_id, book_id, issue_date, due_date, return_date) VALUES
(1, 1, 1, '2026-09-10', '2026-09-24', '2026-09-20'),
(2, 1, 2, '2026-09-25', '2026-10-10', NULL),
(3, 2, 4, '2026-09-15', '2026-09-30', NULL),
(4, 3, 3, '2026-09-01', '2026-09-15', '2026-09-14');